### ISSUE TITLE
i don't know why i can't run your procedure 

### ISSUE THREAD

**Issue by cpxdudu** [sjtu-XutongLu/Blackjack#2]
that's the mistak
176 38  [Error] 'runtime_error' was not declared in this scope
179 9   [Error] expected type-specifier before 'runtime_error'
179 9   [Error] expected type-specifier before 'runtime_error'

**Comment by sjtu-XutongLu** [comment]
Yeah, I forget and use the vs's exception. I will change it into int now.

**Comment by sjtu-XutongLu** [comment]
Have corrected
